### ISSUE TITLE
Support for Chai .not

### ISSUE THREAD

**Issue by bergie** [flowbased/fbp-spec#61]
The chai [.not](http://chaijs.com/api/bdd/#method_not) expectation would be super useful, for example:

```yaml
-
  name: 'listing hashes after removing'
  assertion: 'should not return the same hash'
  inputs:
    pinlist: true
  expect:
    error:
      not:
        contain: 'Qmctf39Vj8aLdg9icf2kvVcENyuNWBwy5TGWvHX9CZ6UkG'
```

Use case: the "listing hashes after removing" test in https://github.com/noflo/noflo-ipfs/blob/master/spec/Pin.yaml
